server:
  port: 8086
spring:
  #通用的数据源配置
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  jpa:
    #这个参数是在建表的时候，将默认的存储引擎切换为 InnoDB 用的
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #配置在日志中打印出执行的 SQL 语句信息。
    show-sql: true
    hibernate:
      #配置指明在程序每次只会更新数据库表里的信息
      ddl-auto: update
  application:
    name: user-server


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
  instance:
    lease-renewal-interval-in-seconds: 30 #设置eureka心跳评率，默认30s
    lease-expiration-duration-in-seconds: 90 #如果过了90s都没有心跳表示服务就挂了，默认90s

#  1：ddl-auto=create-drop 表示当JPA应用的时候自动创建表，在解应用的时候删除相应的表，这个在做测试的时候比较有用，但在开发过程中不这么用
#  2：ddl-auto=create 这个在每次应用启动的时候都会创建数据库表（会删除以前数据库里的数据。
#  3：ddl-auto=update 这个属性的作用是:每次只会更新数据库表里的信息
logging:
  level:
    com.ybmspringbootjpa.jpa: debug